spring:
  application:
    name: eureka-server
server:
  port: 9999

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
  #使用register-with-eureka和fetch-registry都为false来表明自己为一个eureka server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaulZone: http://${eureka.instance.hostname}:${server.port}/eureka/