#服务的注册和发现都是依靠这个name来进行
spring:
  application:
    name: cloud_application
#应用端口号
server:
  port: 9998
#指定eureka注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
