spring:
  application:
    name: config-server
  cloud:
      config:
        server:
          native:
            search-locations: classpath:/config/{application},common
  profiles:
    active: native

server:
  port: 9997
